### ISSUE TITLE
WebRequests, variable operations, lists, enums and arrays

### ISSUE THREAD

**Issue by DeroDev** [VMGP/vppi#1]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you would like**
I would like WebRequests, variable operations, lists, enums and arrays to be added to V++. These feautures would be really helpful to me and other developers working with V++.

**Additional context**
No.

**Comment by VMGP** [comment]
@DeroDev I will work on this! Thanks for the suggestion!
